// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function CheckFalConnection() {
  return window['go']['main']['App']['CheckFalConnection']();
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function CheckOllama(arg1) {
  return window['go']['main']['App']['CheckOllama'](arg1);
}

export function ChooseToolWorkspace(arg1) {
  return window['go']['main']['App']['ChooseToolWorkspace'](arg1);
}

export function ClearOpenAICompatibleAPIKey() {
  return window['go']['main']['App']['ClearOpenAICompatibleAPIKey']();
}

export function CreateLibrary(arg1) {
  return window['go']['main']['App']['CreateLibrary'](arg1);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function DeleteLibrary(arg1) {
  return window['go']['main']['App']['DeleteLibrary'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExecuteTool(arg1) {
  return window['go']['main']['App']['ExecuteTool'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function HasFalAPIKey() {
  return window['go']['main']['App']['HasFalAPIKey']();
}

export function HasOpenAICompatibleAPIKey() {
  return window['go']['main']['App']['HasOpenAICompatibleAPIKey']();
}

export function HasOpenRouterAPIKey() {
  return window['go']['main']['App']['HasOpenRouterAPIKey']();
}

export function InstallUpdate() {
  return window['go']['main']['App']['InstallUpdate']();
}

export function ListConversationAssets(arg1) {
  return window['go']['main']['App']['ListConversationAssets'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListFalImageEditModels() {
  return window['go']['main']['App']['ListFalImageEditModels']();
}

export function ListFalLipsyncImageModels() {
  return window['go']['main']['App']['ListFalLipsyncImageModels']();
}

export function ListFalLipsyncVideoModels() {
  return window['go']['main']['App']['ListFalLipsyncVideoModels']();
}

export function ListFalModels() {
  return window['go']['main']['App']['ListFalModels']();
}

export function ListFalSoundEffectModels() {
  return window['go']['main']['App']['ListFalSoundEffectModels']();
}

export function ListFalSpeechModels() {
  return window['go']['main']['App']['ListFalSpeechModels']();
}

export function ListFalTranscribeModels() {
  return window['go']['main']['App']['ListFalTranscribeModels']();
}

export function ListFalUpscaleModels() {
  return window['go']['main']['App']['ListFalUpscaleModels']();
}

export function ListFalVideoDurations(arg1) {
  return window['go']['main']['App']['ListFalVideoDurations'](arg1);
}

export function ListFalVideoExtendModels() {
  return window['go']['main']['App']['ListFalVideoExtendModels']();
}

export function ListFalVideoImageModels() {
  return window['go']['main']['App']['ListFalVideoImageModels']();
}

export function ListFalVideoModels() {
  return window['go']['main']['App']['ListFalVideoModels']();
}

export function ListFalVideoMotionModels() {
  return window['go']['main']['App']['ListFalVideoMotionModels']();
}

export function ListFalVideoUpscaleModels() {
  return window['go']['main']['App']['ListFalVideoUpscaleModels']();
}

export function ListLibraries() {
  return window['go']['main']['App']['ListLibraries']();
}

export function ListLibraryAssets(arg1) {
  return window['go']['main']['App']['ListLibraryAssets'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListOpenAICompatibleModels(arg1) {
  return window['go']['main']['App']['ListOpenAICompatibleModels'](arg1);
}

export function ListPrimaryModels(arg1, arg2) {
  return window['go']['main']['App']['ListPrimaryModels'](arg1, arg2);
}

export function ListProjectConversations(arg1) {
  return window['go']['main']['App']['ListProjectConversations'](arg1);
}

export function ListToolFiles(arg1) {
  return window['go']['main']['App']['ListToolFiles'](arg1);
}

export function MoveConversationToProject(arg1, arg2) {
  return window['go']['main']['App']['MoveConversationToProject'](arg1, arg2);
}

export function PurgeArchivedConversations() {
  return window['go']['main']['App']['PurgeArchivedConversations']();
}

export function RandomEmptyStatePrompt() {
  return window['go']['main']['App']['RandomEmptyStatePrompt']();
}

export function ReadToolFile(arg1) {
  return window['go']['main']['App']['ReadToolFile'](arg1);
}

export function RenameLibrary(arg1, arg2) {
  return window['go']['main']['App']['RenameLibrary'](arg1, arg2);
}

export function RenameProject(arg1, arg2) {
  return window['go']['main']['App']['RenameProject'](arg1, arg2);
}

export function ResolveToolPermission(arg1, arg2) {
  return window['go']['main']['App']['ResolveToolPermission'](arg1, arg2);
}

export function RunToolCommand(arg1) {
  return window['go']['main']['App']['RunToolCommand'](arg1);
}

export function SaveAudio(arg1) {
  return window['go']['main']['App']['SaveAudio'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveFalAPIKey(arg1) {
  return window['go']['main']['App']['SaveFalAPIKey'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SaveOpenAICompatibleAPIKey(arg1) {
  return window['go']['main']['App']['SaveOpenAICompatibleAPIKey'](arg1);
}

export function SaveOpenRouterAPIKey(arg1) {
  return window['go']['main']['App']['SaveOpenRouterAPIKey'](arg1);
}

export function SaveVideo(arg1) {
  return window['go']['main']['App']['SaveVideo'](arg1);
}

export function SearchConversations(arg1, arg2) {
  return window['go']['main']['App']['SearchConversations'](arg1, arg2);
}

export function SetOllamaBaseURL(arg1) {
  return window['go']['main']['App']['SetOllamaBaseURL'](arg1);
}

export function StreamChat(arg1) {
  return window['go']['main']['App']['StreamChat'](arg1);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function WriteToolFile(arg1) {
  return window['go']['main']['App']['WriteToolFile'](arg1);
}
