// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelStream(arg1:string):Promise<void>;

export function CheckFalConnection():Promise<void>;

export function CheckOllama(arg1:string):Promise<main.OllamaStatus>;

export function ChooseToolWorkspace(arg1:string):Promise<string>;

export function DeleteConversation(arg1:string):Promise<void>;

export function ExecuteTool(arg1:main.ToolExecutionRequest):Promise<main.HarnessToolResult>;

export function GetConfig():Promise<main.AppConfig>;

export function GetConversation(arg1:string):Promise<main.ConversationDetail>;

export function HasFalAPIKey():Promise<boolean>;

export function HasOpenRouterAPIKey():Promise<boolean>;

export function ListConversations():Promise<Array<main.ConversationSummary>>;

export function ListModels(arg1:string):Promise<Array<main.OllamaModel>>;

export function ListPrimaryModels(arg1:string,arg2:string):Promise<Array<main.ModelInfo>>;

export function ListToolFiles(arg1:main.ToolFileListRequest):Promise<main.ToolFileListResult>;

export function PurgeArchivedConversations():Promise<main.PurgeArchivedResult>;

export function ReadToolFile(arg1:main.ToolFileReadRequest):Promise<main.ToolFileReadResult>;

export function ResolveToolPermission(arg1:string,arg2:boolean):Promise<void>;

export function RunToolCommand(arg1:main.ToolCommandRequest):Promise<main.ToolCommandResult>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SaveFalAPIKey(arg1:string):Promise<void>;

export function SaveImage(arg1:main.SaveImageRequest):Promise<string>;

export function SaveOpenRouterAPIKey(arg1:string):Promise<void>;

export function SetOllamaBaseURL(arg1:string):Promise<void>;

export function StreamChat(arg1:main.ChatRequest):Promise<main.ChatStreamStart>;

export function UpdateConversationTitle(arg1:string,arg2:string):Promise<main.ConversationSummary>;

export function WriteToolFile(arg1:main.ToolFileWriteRequest):Promise<main.ToolFileWriteResult>;
