// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function CheckOllama(arg1) {
  return window['go']['main']['App']['CheckOllama'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SetOllamaBaseURL(arg1) {
  return window['go']['main']['App']['SetOllamaBaseURL'](arg1);
}

export function StreamChat(arg1) {
  return window['go']['main']['App']['StreamChat'](arg1);
}
