// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelStream(arg1) {
  return window['go']['main']['App']['CancelStream'](arg1);
}

export function CheckOllama(arg1) {
  return window['go']['main']['App']['CheckOllama'](arg1);
}

export function ChooseToolWorkspace(arg1) {
  return window['go']['main']['App']['ChooseToolWorkspace'](arg1);
}

export function DeleteConversation(arg1) {
  return window['go']['main']['App']['DeleteConversation'](arg1);
}

export function ExecuteTool(arg1) {
  return window['go']['main']['App']['ExecuteTool'](arg1);
}

export function GenerateImage(arg1) {
  return window['go']['main']['App']['GenerateImage'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function ListConversations() {
  return window['go']['main']['App']['ListConversations']();
}

export function ListModels(arg1) {
  return window['go']['main']['App']['ListModels'](arg1);
}

export function ListToolFiles(arg1) {
  return window['go']['main']['App']['ListToolFiles'](arg1);
}

export function PurgeArchivedConversations() {
  return window['go']['main']['App']['PurgeArchivedConversations']();
}

export function ReadToolFile(arg1) {
  return window['go']['main']['App']['ReadToolFile'](arg1);
}

export function ResolveToolPermission(arg1, arg2) {
  return window['go']['main']['App']['ResolveToolPermission'](arg1, arg2);
}

export function RunToolCommand(arg1) {
  return window['go']['main']['App']['RunToolCommand'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['main']['App']['SaveImage'](arg1);
}

export function SetOllamaBaseURL(arg1) {
  return window['go']['main']['App']['SetOllamaBaseURL'](arg1);
}

export function StartImageGeneration(arg1) {
  return window['go']['main']['App']['StartImageGeneration'](arg1);
}

export function StreamChat(arg1) {
  return window['go']['main']['App']['StreamChat'](arg1);
}

export function UpdateConversationTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateConversationTitle'](arg1, arg2);
}

export function WriteToolFile(arg1) {
  return window['go']['main']['App']['WriteToolFile'](arg1);
}
